version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-version-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s4bev8b7k3xe"
s3_prefix = "lambda-version-example"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
disable_rollback = true
