AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LambdaVersionExample

  Sample SAM Template for LambdaVersionExample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  LambdaVersionExampleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LambdaVersionExample
      Handler: com.appsdeveloperblog.aws.lambda.LambdaVersionExample::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        FunctionVersion:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /version
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaVersionExampleFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Lambda Version Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/version"
  LambdaVersionExampleFunction:
    Description: "Lambda Version Function ARN"
    Value: !GetAtt LambdaVersionExampleFunction.Arn
  LambdaVersionExampleFunctionIamRole:
    Description: "Implicit IAM Role created for Lambda Version Function"
    Value: !GetAtt LambdaVersionExampleFunctionRole.Arn
